//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TEntities : DbContext
    {
        public TEntities()
            : base("name=TEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Биомы> Биомы { get; set; }
        public virtual DbSet<История_Обновлений> История_Обновлений { get; set; }
        public virtual DbSet<Классы_персонажей> Классы_персонажей { get; set; }
        public virtual DbSet<Механики> Механики { get; set; }
        public virtual DbSet<Отчивки> Отчивки { get; set; }
        public virtual DbSet<Предметы> Предметы { get; set; }
        public virtual DbSet<Растения> Растения { get; set; }
        public virtual DbSet<Режимы_игры> Режимы_игры { get; set; }
        public virtual DbSet<События> События { get; set; }
        public virtual DbSet<Существа> Существа { get; set; }
        public virtual DbSet<Удалённое> Удалённое { get; set; }
    }
}
