//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Режимы_игры
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Режимы_игры()
        {
            this.События = new HashSet<События>();
        }
    
        public int mode_id { get; set; }
        public string название { get; set; }
        public string описание { get; set; }
        public Nullable<int> update_id { get; set; }
    
        public virtual История_Обновлений История_Обновлений { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<События> События { get; set; }
    }
}
